# Generated by Django 5.2 on 2026-01-30 14:32

import curriculum.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_datospersonales_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de Clasificación',
                'verbose_name_plural': 'Etiquetas de Clasificación',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_inicio', models.BooleanField(default=True, verbose_name='Mostrar Inicio')),
                ('mostrar_perfil', models.BooleanField(default=True, verbose_name='Mostrar Perfil (Datos Personales)')),
                ('mostrar_experiencia', models.BooleanField(default=True, verbose_name='Mostrar Experiencia')),
                ('mostrar_educacion', models.BooleanField(default=True, verbose_name='Mostrar Educación')),
                ('mostrar_cursos', models.BooleanField(default=True, verbose_name='Mostrar Cursos')),
                ('mostrar_logros', models.BooleanField(default=True, verbose_name='Mostrar Logros/Reconocimientos')),
                ('mostrar_trabajos', models.BooleanField(default=True, verbose_name='Mostrar Trabajos')),
                ('mostrar_venta', models.BooleanField(default=True, verbose_name='Mostrar Sección Venta')),
                ('mostrar_contacto', models.BooleanField(default=True, verbose_name='Mostrar Contacto')),
            ],
            options={
                'verbose_name': 'Configuración de Visibilidad',
                'verbose_name_plural': 'Configuración de Visibilidad',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Español', 'Español'), ('Inglés', 'Inglés'), ('Francés', 'Francés'), ('Alemán', 'Alemán'), ('Italiano', 'Italiano'), ('Portugués', 'Portugués'), ('Chino', 'Chino'), ('Japonés', 'Japonés'), ('Ruso', 'Ruso'), ('Otro', 'Otro')], max_length=50, verbose_name='Idioma')),
                ('nivel', models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Elemental'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Maestría'), ('Nativo', 'Nativo')], max_length=20, verbose_name='Nivel de Dominio')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('registro_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID / Registro de Propiedad')),
                ('fecha_publicacion', models.DateField(validators=[curriculum.models.validar_no_futuro], verbose_name='Fecha de Publicación')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='academicos/', verbose_name='Documentación (PDF/Zip)')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible en la web')),
                ('categorias', models.ManyToManyField(blank=True, to='curriculum.categoriatag', verbose_name='Clasificación (Tags)')),
            ],
            options={
                'verbose_name': 'Producto Académico',
                'verbose_name_plural': '4. Producción Intelectual',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.DeleteModel(
            name='ProductoLaboral',
        ),
        migrations.AlterModelOptions(
            name='cursocapacitacion',
            options={'ordering': ['-fecha_realizacion'], 'verbose_name_plural': '5. Cursos y Certificaciones'},
        ),
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'verbose_name': '1. Información de Identidad', 'verbose_name_plural': '1. Información de Identidad'},
        ),
        migrations.AlterModelOptions(
            name='estudiorealizado',
            options={'ordering': ['-fecha_fin'], 'verbose_name': 'Título Académico', 'verbose_name_plural': '3. Formación Académica'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': '2. Trayectoria Profesional'},
        ),
        migrations.AlterModelOptions(
            name='reconocimiento',
            options={'ordering': ['fecha_obtencion'], 'verbose_name_plural': '6. Reconocimientos y Premios'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name_plural': '7. Venta de Garage'},
        ),
        migrations.RemoveField(
            model_name='cursocapacitacion',
            name='certificado_pdf',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='item_id',
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='fecha_realizacion',
            field=models.DateField(null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='intereses',
            field=models.TextField(blank=True, help_text='Ej: Desarrollo web, diseño de interfaces, etc.', null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_seccion',
            field=models.BooleanField(default=True, verbose_name='Sección Activa'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url_tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok URL'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='valores_profesionales',
            field=models.CharField(blank=True, help_text='Valores separados por comas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estudiorealizado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='fecha_obtencion',
            field=models.DateField(null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='horas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcion_perfil',
            field=models.TextField(blank=True, null=True, verbose_name='Bio (Resumen)'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direccion_trabajo',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de Trabajo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, validators=[curriculum.models.validar_fecha_nacimiento]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Licencia'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugar_nacimiento',
            field=models.CharField(default='No especificado', max_length=100, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Otro', 'Otro')], max_length=20, verbose_name='Sexo / Género'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='url_github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='url_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='url_linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='educacion/'),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='fecha_fin',
            field=models.DateField(validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='fecha_inicio',
            field=models.DateField(validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='empresa',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Vacío si es Actual', null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_inicio',
            field=models.DateField(validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='codigo_registro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='institucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='idioma',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='curriculum.datospersonales'),
        ),
    ]
