# Generated by Django 5.2 on 2026-02-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_categoriatag_configuracionpagina_idioma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='modalidad',
            field=models.CharField(choices=[('PRE', 'Presencial'), ('REM', 'Remoto'), ('HIB', 'Híbrido / Mixto')], default='PRE', help_text='Selecciona si el trabajo fue presencial, remoto o mixto.', max_length=3, verbose_name='Modalidad de trabajo'),
        ),
    ]
