# Generated by Django 5.2 on 2026-02-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_experiencialaboral_modalidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': '2. Trayectoria Profesional'},
        ),
        migrations.AlterModelOptions(
            name='reconocimiento',
            options={'ordering': ['-fecha_obtencion'], 'verbose_name_plural': '6. Reconocimientos y Premios'},
        ),
    ]
