# Generated by Django 5.2 on 2026-02-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_alter_experiencialaboral_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursocapacitacion',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cursos/', verbose_name='Certificado (PDF)'),
        ),
    ]
