# Generated by Django 5.2 on 2026-02-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_cursocapacitacion_certificado_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursocapacitacion',
            options={'ordering': ['fecha_realizacion'], 'verbose_name_plural': '5. Cursos y Certificaciones'},
        ),
        migrations.AlterModelOptions(
            name='estudiorealizado',
            options={'ordering': ['fecha_fin'], 'verbose_name': 'Título Académico', 'verbose_name_plural': '3. Formación Académica'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': '2. Trayectoria Profesional'},
        ),
        migrations.AlterModelOptions(
            name='productoacademico',
            options={'ordering': ['fecha_publicacion'], 'verbose_name': 'Producto Académico', 'verbose_name_plural': '4. Producción Intelectual'},
        ),
        migrations.AlterModelOptions(
            name='reconocimiento',
            options={'ordering': ['fecha_obtencion'], 'verbose_name_plural': '6. Reconocimientos y Premios'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'ordering': ['fecha_publicacion'], 'verbose_name_plural': '7. Venta de Garage'},
        ),
    ]
