# Generated by Django 5.2 on 2026-02-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_alter_cursocapacitacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Referencia'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Empresa/Jefe'),
        ),
    ]
