# Generated by Django 5.2 on 2026-02-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_experiencialaboral_nombre_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='experiencia/', verbose_name='Constancia Laboral (PDF)'),
        ),
    ]
