# Generated by Django 5.2 on 2026-02-02 20:28

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_experiencialaboral_certificado_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='fecha_realizacion',
            field=models.DateField(blank=True, null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de actividades'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fecha_obtencion',
            field=models.DateField(blank=True, null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
