# Generated by Django 5.2 on 2026-02-03 07:40

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_alter_cursocapacitacion_fecha_realizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiorealizado',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Deja vacío si cursas actualmente', null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
    ]
